### ISSUE TITLE
Any news? 

### ISSUE THREAD

**Issue by Intecpsp** [FinGameWorks/Changelog#1]
Any news on hosting your apps elsewhere?

**Comment by JustinFincher** [comment]
Hi, please visit diffuse.app again, the app has been hosted directly on the website

**Comment by Intecpsp** [comment]
I got it the other day when you posted it. Is that the final version? No further updates?

**Comment by JustinFincher** [comment]
Unfortunately, it is final for now, I wish I could continue to work on getting my Google Play dev account back and work on new features, but I am just not in the mental state that is capable of doing so due to other changes in my life. I am really sorry for that.

**Comment by Intecpsp** [comment]
All is well, mental health is important. Thank you for what you've done though! Good luck on future projects and I hope everything works out for you in the future!
